// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pqelavffbhqprofqcfis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxZWxhdmZmYmhxcHJvZnFjZmlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMzQzNTcsImV4cCI6MjA2ODYxMDM1N30.JB0LAyE0Ob2xSiSlU-6RC8-XvxU4qQB5l1WBnj5DKmo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});